name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install genbadge[coverage]
      - name: Run tests
        run: pytest --cov=. tests/ -v --cov-report=xml:reports/coverage/coverage.xml
      - name: Generate coverage badge
        run: genbadge coverage -o coverage.svg
      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
      
