name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codecov
      - name: Run tests
        run: pytest --cov=. tests/ --cov-report=xml -v 
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
